services:
  mongodb:
    image: mongo:8.0.6
    container_name: mongodb
    ports:
      - "8087:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: